name: CI
on:
  push:
    branches:
      - main
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: 'x64'
    - name: Run migrations
      run: python manage.py migrate
    - name: Tests
      run: python manage.py test